name: VoidWorld
version: 'v1.0'
main: mc.voidworld.VoidWorld
load: STARTUP
commands:
  createvoidworld:
    description: Create a void world
    usage: /createvoidworld
    default: op
  worldteleport:
    description: Teleport to a world
    usage: /worldteleport [world]
    default: op
